# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf789f0ca8b68e81c4c4d8081db82690406219d30cb008cf0aa54fb1a907b52426e8088f61186ef7cdb3215d457130eda6d6f4da9aa9ba9cc286bdc02a3ee1a2

test:
  secret_key_base: 0f0cf3e48f30d7decbbc3f27969dba75e2ffba2f82cdcb7434269b2e2d8f97e2ec2eb7e8dc212639dece2346db7d92d6002ae9d2c4eca01ad9aa732b66f23df1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
